### ISSUE TITLE
Add new retail manager from existing retailer locations

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard#136]
UI to handle adding a new retail manager and using available retail locations retrieved using output of #97 

Story #11

**Comment by jakepeyser** [comment]
@Austinauth based on our discussion yesterday, this might be invalid. Thoughts?

**Comment by Austinauth** [comment]
@jakepeyser Can you clarify what the question is, I'm not sure I understand entirely.

At this point I'm assuming we want to support the ability to create a new Retail Manager/Location at any given point. I'm not sure we need to support adding a new Retail Manager to a location that already has one.

**Comment by jakepeyser** [comment]
@Austinauth this is for the UX of adding a new retail manager during the demo. All locations will exist from the point of the demo's creation, but no retail managers will be assigned. I believe this is _still_ relevant b/c this will happen from the dashboard "Demo settings" sidebar now

**Comment by Austinauth** [comment]
@jakepeyser Agreed. Since the locations exist from the point of creation then this will almost certainly be needed for the Demo Settings panel.

**Comment by jakepeyser** [comment]
Yes, all demos will be initiated with the same set of data, including retail locations

**Comment by colbycheeze** [comment]
Currently we have the GlobalNav being worked on, which will have the "add new manager" button, however we haven't really fleshed out how a new manager get's added...or how the user chooses a "location" for the manager.

Is there a UX task for this or do we have any thoughts yet? @kingtraceyj @Austinauth 

Is it going to go to another page, a slide out, a modal create window?

Now that I have the data flowing in the app we have a list of existing roles to fill out the global nav, so it's a good time to think about this so that we can build in the feature, but we can't really do anything meaningful without an idea of what the interaction should look like.
