### ISSUE TITLE
Log-in/Entry Experience Design

### ISSUE THREAD

**Issue by kingtraceyj** [IBM-Bluemix/logistics-wizard#148]
Complete UX and Visual of Log-In/Entry experience 

- Supply chain manager
- retail manager
- existing user
- messaging

Story #11 
Reference Steps 2-4: https://ibm.app.box.com/notes/75279614890?view_comment=109461021

**Comment by Austinauth** [comment]
UX placeholder

**Comment by Austinauth** [comment]
Yesterday morning the design team discussed some potential onboarding/entry flow variations with @jakepeyser that have since been captured (an annotated) on our Mural.ly board.

As a team we decided to go with *[Entry Flow V3 - Quick Entry (See: Mural.ly Diagram)](https://app.mural.ly/t/bluemixdeveloperadvocates4089/m/bluemixdeveloperadvocates4089/1470248947358).*

## Quick Entry Flow
The basic premise behind *Entry Flow V3 - Quick Entry* is to ensure the user/demo-giver gets into the demo as quickly as possible (*for annotated screens please refer to the Mural.ly board*). 

![v3-create session](https://cloud.githubusercontent.com/assets/6994218/17406663/01190a56-5a2a-11e6-8223-fd3a7c428f0d.png)

A new user begins at the create session step. Here the user optionally provides a project name and an email.

![v3-dashboard](https://cloud.githubusercontent.com/assets/6994218/17407204/0e919098-5a2c-11e6-857d-61a856681b64.png)

From the create session step the user arrives at the product dashboard as a Supply Chain Manager. In the background a default Retail Manager role(s) is created based off the user's current location.

![v3-dashboard settings](https://cloud.githubusercontent.com/assets/6994218/17407317/702b0906-5a2c-11e6-9fb4-8f789aa2ef27.png)

From the Dashboard the user can navigate to the Demo Settings Panel where they can:
* Switch Roles
* Create a new Retail Manager
* Reset the Demo
* Control Demo Scenarios (like trigger weather alerts)

We believe this entry flow works because it is simple, it gets the user into the product as quickly as possible, and it also provides a persistent way for the user/demo-giver to modify the demo scenario and settings (via the demo settings panel).

**Comment by jakepeyser** [comment]
As we discussed yesterday, we believe this is optimal to get users into the logistics dashboard asap. @uwefassnacht will this work?

**Comment by kingtraceyj** [comment]
HiFi for "create project"

I'm thinking that the "Github source code" copy next to the git icon can go away once you log in to keep from over crowding the nav bar. icon is good to use: https://github.com/logos

![lw - create session](https://cloud.githubusercontent.com/assets/20582179/17411712/0bea9336-5a3f-11e6-8424-56df5d45c476.png)

**Comment by Austinauth** [comment]
@kingtraceyj 
Good call. I'm okay with that. The GitHub icon is pretty iconic (no pun intended 😄).

@jakepeyser Does the proposed copy on this screen Tracey attached seem okay?

**Comment by jakepeyser** [comment]
Visually, great. A few comments on copy:
- I think we should be consistent about location of the GH source code link. If we don't want it on the nav bar in the dashboard, maybe it should _always_ be in the footer?
- I think we need a brief explanation of this step as the main copy. Here's a start: "Fill out this small form so we can create a brand new, isolated demo environment just for you"
- re email address. We need to note that we are not storing the email address. I think that copy can be condensed and simply included as a tooltip near the label of that field: "We do not store your email address and promise never to bug you. We simply send a welcome email with your unique session ID and other demo info."
- copy on link retrieval: "Already created a **session**? You can access a **previously** created session using the link **in your welcome email**.

Thoughts?

**Comment by Austinauth** [comment]
@jakepeyser 

> I think we should be consistent about location of the GH source code link. If we don't want it on the nav bar in the dashboard, maybe it should always be in the footer?

I think we *do* want it on the navbar in the dashboard (for consistency). We would just potentially remove the *GitHub Source Code* copy in favor of the GitHub icon.

> I think we need a brief explanation of this step as the main copy. Here's a start: "Fill out this small form so we can create a brand new, isolated demo environment just for you"
I like this. We can draft up something.

> re email address. We need to note that we are not storing the email address. I think that copy can be condensed and simply included as a tooltip near the label of that field: "We do not store your email address and promise never to bug you. We simply send a welcome email with your unique session ID and other demo info."
Agreed.

> copy on link retrieval: "Already created a session? You can access a previously created session using the link in your welcome email.
Agreed.

**Comment by jakepeyser** [comment]
Any updated screens for this?

**Comment by kingtraceyj** [comment]
@Austinauth and i are thinking that changing the heading to "create demo session" will be more directive than get started. that way we can keep the email copy outside of a tool tip.

![lw - create session](https://cloud.githubusercontent.com/assets/20582179/17635698/808bd1b8-609e-11e6-90a0-909a8d57fc82.png)

mobile comp:
![create session - mobile](https://cloud.githubusercontent.com/assets/20582179/17635791/25517dce-609f-11e6-9d44-15852964fa7f.png)

**Comment by jakepeyser** [comment]
Looks like we never incorporated the [changes agreed here](https://github.com/IBM-Bluemix/logistics-wizard/issues/148#issuecomment-237643372), is this still in the works? I know Colby has already implemented most, if not all, of this screen

attn: @Austinauth @kingtraceyj

**Comment by Austinauth** [comment]
@jakepeyser

I think most of the above has been addressed.

 > I think we should be consistent about location of the GH source code link. If we don't want it on the nav bar in the dashboard, maybe it should always be in the footer?

GitHub link is consistently in the global header.

> I think we need a brief explanation of this step as the main copy. Here's a start: "Fill out this small form so we can create a brand new, isolated demo environment just for you".

Adding this extra copy word-for-word makes this page super text heavy. @kingtraceyj and I changed the title statement from *Let's Get Started" to "Create Demo Session". We believe this encapsulates the sentiment of your original concern without having to add in another line of copy.

> re email address. We need to note that we are not storing the email address. I think that copy can be condensed and simply included as a tooltip near the label of that field: "We do not store your email address and promise never to bug you. We simply send a welcome email with your unique session ID and other demo info."

@kingtraceyj will take another look at this.

> copy on link retrieval: "Already created a session? You can access a previously created session using the link in your welcome email.

This has been added to the [latest screens](https://github.com/IBM-Bluemix/logistics-wizard/issues/148#issuecomment-239548439)

**Comment by jakepeyser** [comment]
Thanks for clarifying, Austin. My thought was that "Fill out this small form so we can create a brand new, isolated demo environment just for you" or something similar replaces the email copy. I'll ultimately leave that up to your judgement.

I was mostly talking about the latter two, so just keep the FEDs in sync. I was going off of what was being shared in the current meeting!

**Comment by colbycheeze** [comment]
Issue moved to [IBM-Bluemix/logistics-wizard-webui #1](https://github.com/IBM-Bluemix/logistics-wizard-webui/issues/1) via [**ZenHub**](https://www.zenhub.com/)
