### ISSUE TITLE
Create a toolchain for logistics-wizard-UI

### ISSUE THREAD

**Issue by rvennam** [IBM-Bluemix/logistics-wizard#190]
Need a toolchain for UI, similar to controller and ERP

**Comment by l2fprod** [comment]
toolchain updated with webui with two steps BUILD and DEPLOY. Build runs the tests and creates the "dist" folder. Due to the size of the node_modules folder (200MB), building then passing the artifacts to test takes too long so I merged the two steps.

No coverage published yet there - we can add this later. First goal is really to get the web ui pushed automatically if tests are OK. Another aspect we can look at is how to speed up the transition between BUILD and DEPLOY by only putting "dist" as the artifact folder. In that case, we need to copy the manifest to the dist folder too.

@rvennam @colbycheeze I need to be added as project owner for webui to add the Git webhook.
