### ISSUE TITLE
Decide Experience for Viewing UI for Two Roles

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard#54]
We need to determine how users will be able to experience both personas' views and data when they log into the demo. Do they log into both at the same time? Do they share workspaces between logins?

Story #11

**Comment by JakePeyser** [comment]
Similar to my comment in #30, this has been documented in the [Demo Sessions wiki page](https://github.com/IBM-Bluemix/logistics-wizard/wiki/Demo-Sessions). @benrondeau I imagine that you would use two browser windows to play both roles at the same time. Do you think this is fine from a UX perspective?

**Comment by benrondeau** [comment]
Sure. From a UX perspective, that works fine (of course, this assumption will need to be validated with user testing).

The tricky part though is that if they are using the same browser to display both windows, it may become complicated for the browser to remember which data needs to be rendered in each window since they will both have the same cookies/sessions stored on them.

**Comment by JakePeyser** [comment]
It should not be possible for them to login as two different users at the same time on the same browser based on our current solution.

**Comment by benrondeau** [comment]
User's try crazy stuff.... a rare outside possibility. Maybe impossible depending how we set it up
