### ISSUE TITLE
Decide on UI Framework

### ISSUE THREAD

**Issue by benrondeau** [IBM-Bluemix/logistics-wizard#65]
Need to decide on UI framework (technical framework that supports UI). This issue focus on the client side logic (JavaScript).

**JS Framework Requirements:**
- Needs to be able generate views initially and update as data changes 
- Needs to have AJAX support that ideally integrates with UI rendering well.
- Needs to support real time communication of some kind (like web sockets) so UI is accurate to server data.
- Ideally this framework can render on client and server-side (negating the need for two separate frameworks) for ultimate flexibility and reuse.

**My Thoughts:**
- [Meteor.js](https://www.meteor.com/). It handles the above requirements well, and also handles the server side for an all-inclusive framework. The downside will be the learning curve of this framework for us and users, [hurdles deploying to Bluemix](https://www.ibm.com/developerworks/community/blogs/7cce3ca0-2e7b-4603-90c5-570b646f0dd7/entry/meteor_part_6_deployment_bluemix?lang=en), and amount of control handed over to this framework that could prevent us from customizing this app the way we want it.
- [Angular2](https://angular.io/). Most popular JS framework out there that handles all requirements except for integrated real-time communication. This would have to be added with something like [Pusher](https://pusher.com/).

Thoughts from the team?

**Comment by JakePeyser** [comment]
Solid list of requirements. I would add that the framework should handle state update events coming from anywhere, whether client or server.

I would also throw [React](https://facebook.github.io/react/) into the mix with a state container like [Redux](http://redux.js.org/) or [Flux](https://facebook.github.io/flux/) and bundle up modules we need using [webpack](https://webpack.github.io/). I've never used Meteor or Angular, but the dispatch mechanism provided by this framework would make handling state updates between different views (supply chain manager and retail store manager) pretty simple.

**Comment by benrondeau** [comment]
I'd like to avoid React since it is just the view layer. It doesn't handle logic and so you have to add on other components, which adds complexity. The main benefit of React is knowing exactly how it will render (hence the `jsx` syntax) which is critical on a massive site like Facebook, but given the size of our site, that feature is not critical. Having bundled view rendering and logic is more important in my view.

**Comment by JakePeyser** [comment]
I'd say there are other benefits to the modularization of React/Redux, but I am fine with using another framework as I do agree it is complex. Is it difficult to use Meteor w/o Mongo? Hooking it up to the ERP data would be my biggest concern there. It looks like Angular is the way to go imho.

**Comment by benrondeau** [comment]
Mongo can be integrated with Meteor easily - they have packages (like npm does for node) for that

**Comment by JakePeyser** [comment]
No I am saying we will be using Meteor **_w/o_** Mongo...so how would that work?

**Comment by benrondeau** [comment]
Ah. I'll look into that...

**Comment by benrondeau** [comment]
@l2fprod and @JakePeyser - has consideration been given for how the ERP server will publish data to clients? Some sort of publisher/subscriber flow needs to be setup so that clients are kept up to date with the server, but it will need to also work from client to server. Given the real-time nature of this application, the client side and server must be kept in sync and not sure what y'all had in mind for that.

Thoughts?

**Comment by JakePeyser** [comment]
Agreed, this is very important. I have not given much thought to a solution yet, tho. One thought was to leverage  [Zookeeper Watches](https://zookeeper.apache.org/doc/r3.4.5/zookeeperProgrammers.html#ch_zkWatches) so we get both service discovery and real-time updates using the same service. I've never used it, however.

**Comment by benrondeau** [comment]
@jakepeyser and @l2fprod - what are your thoughts about integrating a real-time protocol (like web sockets) and publisher/subscriber module in the controller server to facilitate real-time updates to the UI as other clients change data in a session? Or should it be a separate component (additional web server) from the controller?

**Comment by jakepeyser** [comment]
I am leaning towards incorporating this into the controller as it is already brokering all client requests (and data) and therefore would be able to trigger any events when a request is made. However, I would need to evaluate a potential solution from each side in order to fully consider the pros/cons of either.

**Comment by jakepeyser** [comment]
Based on the conversation this morning with Eldridge, @l2fprod @benrondeau and @blumareks, we will be evaluating Angular2 as the front end framework for the demo. This will work in conjunction with [PubNub](https://www.pubnub.com/developers/angularjs/) or [Reappt](http://developer.reappt.io/docs/manual/html/developerguide/apis/javascript/getting_started.html), which will be evaluated in both #108 and #109

**Comment by benrondeau** [comment]
Reappt doesn't even have a python SDK, so maybe that ends the discussion here? Unless a proxy server is the best option.

**Comment by jakepeyser** [comment]
We shouldn't rule it out just because an SDK doesn't exist. However, that definitely weighs into the evaluation

**Comment by blumareks** [comment]
I will check the availability easiness of the integration with / without SDK for both PubNub and Reappt (#108, #109) - while service is written in py

**Comment by jakepeyser** [comment]
Reappt does not publish their API, so it will not be possible to use Python w/o reverse engineering which is not worth the effort given the robustness of PubNub's Python SDK

**Comment by colbycheeze** [comment]
I would push very strongly for React / Redux. This would provide the most productive coding environment for the team for speed of development, readability, and ease of testing.

Redux and socket.io could be used on the backend for the real time messaging portion.

I've done a lot of development in Meteor building a corporate phone app and other projects before coming to IBM, and that framework has grown up a lot since then (now supporting NPM ecosystem, and works REALLY well now with webpack / react). That could be an "easier" alternative to using socket.io if you are happy with sticking to mongoDB. It makes communicating between front end / back end very quick and easy from a rapid development point of view.

**Comment by jakepeyser** [comment]
- Meteor is off the table as MongoDB is not an option
- Socket.io is not intrinsically distributed or scalable, so it does fit in well with our scenario. Using a pub/sub queue with abstracted load balancing/scaling/routing is more apt for the workloads we would theoretically be dealing with, which is why research into a potential solution is covered by a separate topic in #108 and #109 
- I am on board with React/Redux over Angular, but I'll leave that decision to the popular vote among FEDs

**Comment by l2fprod** [comment]
Also make sure to consider learning curve, readability and popularity of the framework we pick among our target audience.

**Comment by colbycheeze** [comment]
Moving this to closed. We will be going with React / Redux. Setting everything up right now, but I'll create another issue for that.
